# Generated by Django 3.2.7 on 2021-09-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HatData',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
                ('Temperature', models.DecimalField(blank=True, db_column='Temperature', decimal_places=1, max_digits=3, null=True)),
                ('Humidity', models.IntegerField(blank=True, db_column='Humidity', null=True)),
                ('Pressure', models.DecimalField(blank=True, db_column='Pressure', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'HatData',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LastSeenId',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('LastSeenId', models.CharField(blank=True, db_column='LastSeenId', max_length=19, null=True)),
                ('User', models.CharField(blank=True, db_column='User', max_length=150, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LastSeenId',
                'managed': True,
            },
        ),
    ]
