# Generated by Django 3.2.7 on 2021-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastseenid',
            name='trip_number',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
