# Generated by Django 3.2.7 on 2021-09-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_lastseenid_trip_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastseenid',
            old_name='trip_number',
            new_name='img_link',
        ),
    ]
