# Generated by Django 3.2.7 on 2021-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_trip_number_lastseenid_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastseenid',
            name='img_link',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
