# Generated by Django 3.2.7 on 2021-09-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_lastseenid_img_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSeenTweet',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Tweet_id', models.CharField(blank=True, db_column='LastSeenId', max_length=19, null=True)),
                ('User', models.CharField(blank=True, db_column='User', max_length=150, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('img_link', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('Tweet', models.CharField(blank=True, max_length=280, null=True)),
            ],
            options={
                'db_table': 'LastSeenTweet',
                'managed': True,
            },
        ),
    ]
