# Generated by Django 3.2.7 on 2021-09-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_lastseentweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastseenid',
            name='Tweet',
            field=models.CharField(blank=True, default=None, max_length=280, null=True),
        ),
    ]
