# Generated by Django 3.2.7 on 2021-09-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_lastseenid_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Picture', models.ImageField(upload_to='media/')),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='LastSeenTweet',
        ),
    ]
