# Generated by Django 3.2.7 on 2021-09-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210910_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='Picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
